version: '3.1'
services:
  db:
    image: mysql
    container_name: locadora_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - locadora_data:/var/lib/mysql
volumes:
  locadora_data:

